name:                elliptic-curve
version:             0.1.0.0
github:              "23prime/elliptic-curve"
license:             BSD3
author:              "Okkey"
maintainer:          "a23b23c23d23e@gmail.com"
copyright:           "2019 Okkey"

extra-source-files:
- README.md

synopsis:            Elliptic curve library for Haskell
category:            Math

description:         Please see the README on GitHub at <https://github.com/githubuser/elliptic-curve#readme>

dependencies:
- base >= 4.7 && < 5
- time
- random
- hmatrix
- arithmoi

library:
  source-dirs: Math

tests:
  ellipse-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ellipse
